# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HisXSZBv4jm4mNIFdwopHmmWIqZX57gb
"""

# 1. User Login Check using hardcoded value

username = "admin"
password = "1234"

input_username = "admin"
input_password = "1234"

if input_username == username and input_password == password:
    print("Login Successful")
else:
    print("Invalid Credentials")

# 2. Pass / Fail Analyzer

marks = [45, 78, 90, 33, 60]

pass_count = 0
fail_count = 0

for mark in marks:
    print("Mark:", mark)
    if mark >= 50:
        pass_count += 1
    else:
        fail_count += 1

print()
print("Total Pass Students:", pass_count)
print("Total Fail Students:", fail_count)

# 3. Simple Data Cleaner using array of names

names = [" Alice ", "bob", " CHARLIE "]

new_names = []

for name in names:

    cleaned_name = name.strip().lower()
    new_names.append(cleaned_name)

print("Cleaned Names:", new_names)

# 4. Message Length Analyzer using array of messages

messages = ["Hi", "Welcome to the platform", "OK"]

for message in messages:

    length = len(message)

    print("Message:", message)
    print("Length:", length)

    if length > 10:
        print("This message is longer than 10 characters")

    print()

# 5. Error Message Detector where we use the array of logs for testing

logs = ["INFO", "ERROR", "WARNING", "ERROR"]

count = 0

for log in logs:

    if log == "ERROR":
        print("ERROR DETECTED")
        count += 1

print("Total ERROR entries:", count)